In [1]:
print("Hello")

Hello

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df=pd.read_csv("../data/Data.csv")
df
#df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1      NaN  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [10]:
#first 5 lines
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1      NaN  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [11]:
#last 5 lines
df.tail()

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [14]:
df.shape

(10, 4)

In [ ]:
#df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='str')

In [16]:
df.dtypes

Country          str
Age          float64
Salary       float64
Purchased        str
dtype: object

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    9 non-null      str
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str
dtypes: float64(2), str(2)
memory usage: 452.0 bytes

In [18]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [19]:
df.isnull().sum()

Country      1
Age          1
Salary       1
Purchased    0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [25]:
#split independent variables
#loc uses labels
#iloc uses integer psitions(no from 0 to len of the data)
#we will seperate the dependent and independent variables using split in ml data preprocessing for using in ml model
df
x=df.iloc[:,:-1].values
x

array([['France', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [28]:
x1=df.loc[:,['Country', 'Age', 'Salary']]
x1

   Country   Age   Salary
0   France  44.0  72000.0
1      NaN  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
#split dependent variable
y=df.iloc[:,-1].values
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

In [31]:
#Taking care of misssing of values
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,1:3])
x[:, 1:3]=imputer.transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [32]:
#Encoding categorical data
#encoding the independent variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
Labelencoder_x=LabelEncoder()
x[:,0]=Labelencoder_x.fit_transform(x[:,0])
print(x)

[[0 44.0 72000.0]
 [3 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]

In [ ]:
Labelencoder_y=LabelEncoder()
y=Labelencoder_y.fit_transform(y) #since it's only one columns so use directly without using slicing
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [35]:
#encoding independent variable trough OneHotEncoding which will give in 0 and 1 instead of numbers for every diffrent one
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("Country", OneHotEncoder(), [0])],remainder="passthrough")
x=ct.fit_transform(x)
print(x)
x.astype(int)

[[0.0 1.0 0.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 0.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 0.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 37.0 67000.0]]

array([[    0,     1,     0,     0,     0,    44, 72000],
       [    1,     0,     0,     0,     1,    27, 48000],
       [    1,     0,     1,     0,     0,    30, 54000],
       [    1,     0,     0,     1,     0,    38, 61000],
       [    1,     0,     1,     0,     0,    40, 63777],
       [    0,     1,     0,     0,     0,    35, 58000],
       [    1,     0,     0,     1,     0,    38, 52000],
       [    0,     1,     0,     0,     0,    48, 79000],
       [    1,     0,     1,     0,     0,    50, 83000],
       [    0,     1,     0,     0,     0,    37, 67000]])

In [36]:
#Split data into Training and Test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=11)#use random state to get the consitent result

In [37]:
x_test

array([[0.0, 1.0, 0.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 50.0, 83000.0]], dtype=object)

In [38]:
x_test.astype(int)

array([[    0,     1,     0,     0,     0,    48, 79000],
       [    1,     0,     1,     0,     0,    50, 83000]])

In [ ]:
#feature scaling
#sc_x=(x[1]-mean) / standatd deviation
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
#fit_transform calculates the transformation parameters and applies them immediately, whereas transform applies previously calculated parameters without changing them

In [40]:
x_test

array([[-1.29099445,  1.29099445, -0.57735027, -0.57735027, -0.37796447,
         2.29703199,  2.59208492],
       [ 0.77459667, -0.77459667,  1.73205081, -0.57735027, -0.37796447,
         2.68709402,  3.1230383 ]])

In [41]:
x_train

array([[ 0.77459667, -0.77459667,  1.73205081, -0.57735027, -0.37796447,
        -1.21352633, -0.72637373],
       [ 0.77459667, -0.77459667, -0.57735027,  1.73205081, -0.37796447,
         0.4984126 , -0.99185042],
       [ 0.77459667, -0.77459667,  1.73205081, -0.57735027, -0.37796447,
         0.73678385,  0.57151232],
       [-1.29099445,  1.29099445, -0.57735027, -0.57735027, -0.37796447,
        -0.23837124, -0.19542034],
       [ 0.77459667, -0.77459667, -0.57735027, -0.57735027,  2.64575131,
        -1.79861939, -1.5228038 ],
       [ 0.77459667, -0.77459667, -0.57735027,  1.73205081, -0.37796447,
         0.34672181,  0.20279469],
       [-1.29099445,  1.29099445, -0.57735027, -0.57735027, -0.37796447,
         1.51690792,  1.6629165 ],
       [-1.29099445,  1.29099445, -0.57735027, -0.57735027, -0.37796447,
         0.15169079,  0.99922477]])