In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv("/home/msis/aml_lab/data/Groceries_dataset.csv")
df
#df.head()

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]

In [6]:
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [7]:
df.tail()

       Member_number        Date        itemDescription
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

In [8]:
df.sample(10)

       Member_number        Date  itemDescription
23340           3635  04-09-2015      brown bread
12534           2446  24-09-2014         cake bar
28685           2802  28-07-2014      canned beer
26916           3716  13-05-2014      chewing gum
9273            2204  13-06-2014          chicken
21746           3967  21-01-2015  root vegetables
25687           2453  06-06-2014       whole milk
21575           2265  25-09-2015      soft cheese
12051           1110  11-12-2014             soda
7999            1355  28-02-2015   tropical fruit

In [9]:
df.shape

(38765, 3)

In [10]:
df.columns

Index(['Member_number', 'Date', 'itemDescription'], dtype='str')

In [11]:
df.dtypes

Member_number      int64
Date                 str
itemDescription      str
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  str
 2   itemDescription  38765 non-null  str
dtypes: int64(1), str(2)
memory usage: 908.7 KB

In [13]:
df.describe()

       Member_number
count   38765.000000
mean     3003.641868
std      1153.611031
min      1000.000000
25%      2002.000000
50%      3005.000000
75%      4007.000000
max      5000.000000

In [14]:
df.isnull().sum()

Member_number      0
Date               0
itemDescription    0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(759)

In [18]:
df=df.drop_duplicates()
df

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38006 rows x 3 columns]

In [19]:
df.shape

(38006, 3)