In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.Series([78,85,92,67,88])
df

0    78
1    85
2    92
3    67
4    88
dtype: int64

In [4]:
df.describe()

count     5.000000
mean     82.000000
std       9.823441
min      67.000000
25%      78.000000
50%      85.000000
75%      88.000000
max      92.000000
dtype: float64

In [5]:
df.values

array([78, 85, 92, 67, 88])

In [6]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
df.dtypes

dtype('int64')

In [10]:
df.max()

np.int64(92)

In [11]:
df.min()

np.int64(67)

In [12]:
df.mean()

np.float64(82.0)

In [18]:
marks = pd.Series(
    [85, 78, 92, 85, 88],
    index=["Asha", "Ravi", "Meena", "Asha", "Arun"]
)

In [19]:
marks

Asha     85
Ravi     78
Meena    92
Asha     85
Arun     88
dtype: int64

In [20]:
print(marks["Meena"])

92

In [32]:
quest3=pd.DataFrame({
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
})

In [25]:
print("Complete DataFrame:")
quest3

Complete DataFrame:

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

In [27]:
print("\nFirst 3 rows:")
print(df.head(3))

First 3 rows:
0    78
1    85
2    92
dtype: int64

In [28]:
print("\nLast 2 rows:")
df.tail(2)

Last 2 rows:

3    67
4    88
dtype: int64

In [33]:
quest3.shape

(6, 3)

In [34]:
quest3.columns

Index(['Name', 'Department', 'Marks'], dtype='str')

In [35]:
quest3.dtypes

Name            str
Department      str
Marks         int64
dtype: object

In [38]:
quest4=quest3

In [39]:
quest4

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

In [40]:
quest4.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Marks       6 non-null      int64
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [41]:
quest4.describe()

           Marks
count   6.000000
mean   82.833333
std     6.705719
min    74.000000
25%    78.500000
50%    82.500000
75%    87.250000
max    92.000000

In [44]:
#method 1
rows, columns = quest4.shape
print("Rows:", rows)
print("Columns:", columns)

Rows: 6
Columns: 3

In [ ]:
#method2
print(len(quest4)) #rows
print(len(quest4.columns)) #columns

6
3

In [50]:
quest5=quest3
quest5

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

In [76]:
quest5["Name"]

0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
5    Divya
Name: Name, dtype: str

In [77]:
quest5.iloc[:,0]

0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
5    Divya
Name: Name, dtype: str

In [78]:
quest5.iloc[:,1]

0    CSE
1    ECE
2    CSE
3     ME
4    ECE
5    CSE
Name: Department, dtype: str

In [79]:
quest5.iloc[:,[0,2]]

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88
5  Divya     80

In [80]:
quest6=quest4

In [81]:
quest6

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

In [82]:
quest6.iloc[0:1,]

   Name Department  Marks
0  Asha        CSE     85

In [83]:
quest6.iloc[2:3,]

    Name Department  Marks
2  Meena        CSE     92

In [84]:
quest6.iloc[1:4]

    Name Department  Marks
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74

In [85]:
quest6.loc[:,["Name","Marks"]]

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88
5  Divya     80

In [86]:
quest7=quest6
quest7

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

In [96]:
quest7[quest7["Marks"]>80]

    Name Department  Marks
0   Asha        CSE     85
2  Meena        CSE     92
4   Arun        ECE     88

In [97]:
quest7[(quest7["Marks"]>=75) &(quest7["Marks"]<=90)]

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
4   Arun        ECE     88
5  Divya        CSE     80

In [98]:
quest7[quest7["Department"]=="CSE"]

    Name Department  Marks
0   Asha        CSE     85
2  Meena        CSE     92
5  Divya        CSE     80

In [99]:
quest7[(quest7["Department"]=="CSE") & (quest7["Marks"]>80)]

    Name Department  Marks
0   Asha        CSE     85
2  Meena        CSE     92

In [100]:
quest8=quest7
quest8

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

In [101]:
quest8[(quest8["Department"]=="CSE") | (quest8["Department"]=="ECE")]

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
4   Arun        ECE     88
5  Divya        CSE     80

In [102]:
quest9=quest8

In [104]:
quest9["Result"]=quest9["Marks"].apply(lambda x: "Pass" if x>=75 else "Fail")
quest9

    Name Department  Marks Result
0   Asha        CSE     85   Pass
1   Ravi        ECE     78   Pass
2  Meena        CSE     92   Pass
3  Kiran         ME     74   Fail
4   Arun        ECE     88   Pass
5  Divya        CSE     80   Pass

In [105]:
quest10=quest9

In [107]:
conditions=[ quest10["Marks"]>=90, quest10["Marks"]>=80, quest10["Marks"]>=70]
grades=["A","B","C"]
quest10["Grades"]=np.select(conditions,grades,default="D")
quest10

    Name Department  Marks Result Grades
0   Asha        CSE     85   Pass      B
1   Ravi        ECE     78   Pass      C
2  Meena        CSE     92   Pass      A
3  Kiran         ME     74   Fail      C
4   Arun        ECE     88   Pass      B
5  Divya        CSE     80   Pass      B

In [108]:
quest11=quest10

In [109]:
quest11.sort_values("Marks", ascending=True)

    Name Department  Marks Result Grades
3  Kiran         ME     74   Fail      C
1   Ravi        ECE     78   Pass      C
5  Divya        CSE     80   Pass      B
0   Asha        CSE     85   Pass      B
4   Arun        ECE     88   Pass      B
2  Meena        CSE     92   Pass      A

In [110]:
quest11.sort_values("Marks", ascending=False)

    Name Department  Marks Result Grades
2  Meena        CSE     92   Pass      A
4   Arun        ECE     88   Pass      B
0   Asha        CSE     85   Pass      B
5  Divya        CSE     80   Pass      B
1   Ravi        ECE     78   Pass      C
3  Kiran         ME     74   Fail      C

In [111]:
quest11.sort_values(["Department", "Marks"])

    Name Department  Marks Result Grades
5  Divya        CSE     80   Pass      B
0   Asha        CSE     85   Pass      B
2  Meena        CSE     92   Pass      A
1   Ravi        ECE     78   Pass      C
4   Arun        ECE     88   Pass      B
3  Kiran         ME     74   Fail      C

In [129]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

In [130]:
students1=students

In [113]:
students

    Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

In [114]:
students.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

In [115]:
students.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [116]:
students[students.isnull().any(axis=1)]

    Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

In [118]:
students["Age"]=students["Age"].fillna(students["Age"].mean())
students

    Name    Age  Marks
0   Asha  22.00   85.0
1   Ravi  23.00    NaN
2  Meena  22.75   92.0
3  Kiran  24.00   74.0
4   Arun  22.00   88.0

In [120]:
students["Marks"]=students["Marks"].fillna(students["Marks"].mean())
students

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

In [133]:
students1=students1.dropna()
students1

    Name   Age  Marks
0   Asha  22.0   85.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

In [134]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}
quest15=pd.DataFrame(data)

In [135]:
quest15

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3   Asha     85
4   Arun     88

In [139]:
quest15.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [138]:
quest15[quest15.duplicated()]

   Name  Marks
3  Asha     85

In [140]:
quest15=quest15.drop_duplicates()
quest15

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

In [141]:
marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})
marks

  Student  Marks
0       A     78
1       B     85
2       C     92
3       D     67
4       E     88

In [144]:
marks["Marks"].mean()

np.float64(82.0)

In [145]:
marks["Marks"].median()

np.float64(85.0)

In [146]:
marks["Marks"].max()

np.int64(92)

In [147]:
marks["Marks"].min()

np.int64(67)

In [148]:
marks["Marks"].std()

np.float64(9.82344135219425)

In [149]:
marks["Marks"].sum()

np.int64(410)

In [150]:
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}
quest17=pd.DataFrame(data)
quest17

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

In [151]:
quest17["Marks"].mean()

np.float64(82.83333333333333)

In [154]:
quest17["Marks"].max()

np.int64(92)

In [155]:
quest17.groupby("Department")["Marks"].mean()

Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

In [156]:
quest17.groupby("Department")["Marks"].max()

Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

In [158]:
quest17.groupby("Department")["Name"].count()

Department
CSE    3
ECE    2
ME     1
Name: Name, dtype: int64

In [159]:
students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})
students

   StudentID   Name
0        101   Asha
1        102   Ravi
2        103  Meena
3        104  Kiran

In [160]:
marks

   StudentID  Marks
0        101     85
1        102     78
2        103     92
3        104     74

In [163]:
result=pd.merge(students,marks, on="StudentID")
result

   StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

In [165]:
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)
df

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
6   John         ME          72        70          68
7  Priya        ECE          95        91          93

In [169]:
df.head()

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83

In [166]:
df.shape

(8, 5)

In [168]:
df["FinalMarks"].mean()

np.float64(81.625)

In [171]:
df.loc[df["FinalMarks"].idxmax()]

Name          Meena
Department      CSE
Attendance       96
Internal         94
FinalMarks       96
Name: 2, dtype: object

In [174]:
df.loc[df["FinalMarks"].idxmin()]

Name          Kiran
Department       ME
Attendance       68
Internal         65
FinalMarks       62
Name: 3, dtype: object

In [175]:
df[df["FinalMarks"]>80]

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

In [176]:
df.groupby("Department")["FinalMarks"].mean()

Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

In [177]:
df[df["Attendance"]>80]

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

In [178]:
df.sort_values("FinalMarks")

    Name Department  Attendance  Internal  FinalMarks
3  Kiran         ME          68        65          62
6   John         ME          72        70          68
1   Ravi        ECE          75        72          74
4   Arun        ECE          82        80          83
0   Asha        CSE          92        85          88
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
2  Meena        CSE          96        94          96

In [180]:
df["Result"]=np.where(df["FinalMarks"]>=70,"Pass","Fail")
df

    Name Department  Attendance  Internal  FinalMarks Result
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

In [181]:
conditions=[df["FinalMarks"]>=90,df["FinalMarks"]>=80,df["FinalMarks"]>=70]
categories=["Excellent","Very Good","Good"]

df["Performance"]=np.select(conditions,categories,default="Needs Improvement")
df

,Name,Department,Attendance,Internal,FinalMarks,Result,Performance
0,Asha,CSE,92,85,88,Pass,Very Good
1,Ravi,ECE,75,72,74,Pass,Good
2,Meena,CSE,96,94,96,Pass,Excellent
3,Kiran,ME,68,65,62,Fail,Needs Improvement
4,Arun,ECE,82,80,83,Pass,Very Good
5,Divya,CSE,88,86,89,Pass,Very Good
6,John,ME,72,70,68,Fail,Needs Improvement
7,Priya,ECE,95,91,93,Pass,Excellent

In [182]:
avg_by_dept=df.groupby("Department")["FinalMarks"].mean()
avg_by_dept

Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

In [183]:
employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})
employees

  Employee Department  Experience  Salary
0      E01         IT           5   60000
1      E02         HR           3   45000
2      E03         IT           7   75000
3      E04    Finance           4   65000
4      E05         HR           6   55000
5      E06    Finance           8   85000
6      E07         IT           2   48000
7      E08    Finance           5   70000

In [184]:
employees["Salary"].mean()

np.float64(62875.0)

In [186]:
employees["Salary"].max()

np.int64(85000)

In [187]:
employees["Salary"].min()

np.int64(45000)

In [190]:
employees.loc[employees["Salary"].idxmax()]

Employee          E06
Department    Finance
Experience          8
Salary          85000
Name: 5, dtype: object

In [191]:
employees[employees["Salary"]>60000]

  Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

In [192]:
employees.groupby("Department")["Salary"].mean()

Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

In [193]:
employees.groupby("Department")["Experience"].mean()

Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

In [195]:
employees.groupby("Department")["Employee"].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [196]:
employees.sort_values("Salary")

  Employee Department  Experience  Salary
1      E02         HR           3   45000
6      E07         IT           2   48000
4      E05         HR           6   55000
0      E01         IT           5   60000
3      E04    Finance           4   65000
7      E08    Finance           5   70000
2      E03         IT           7   75000
5      E06    Finance           8   85000

In [197]:
employees[(employees["Department"]=="IT") & (employees["Experience"]>3)]

  Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000

In [198]:
conditions=[employees["Salary"]>=75000,employees["Salary"]>=50000]
levels=["High","Medium"]
employees["SalaryLevel"]=np.select(conditions,levels,default="Low")
employees

  Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium