In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

In [3]:
df=pd.read_csv("/home/msis/aml_lab/data/Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
X=df.iloc[:,2:4]
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [5]:
y=df.loc[:,['Purchased']]
y

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [6]:
dt_classifier = DecisionTreeClassifier(random_state=42, max_depth=3)

kf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

In [7]:
cv_scores = cross_val_score(dt_classifier, X, y, cv=kf, scoring='accuracy')

print("Accuracy scores for each fold:", cv_scores)
print(f"Average Accuracy: {cv_scores.mean() * 100:.2f}%")

Accuracy scores for each fold: [0.92537313 0.87969925 0.92481203]
Average Accuracy: 91.00%